

# Store the current CFBundleVersion and CFBundleShortVersionString in the fastlane context before every lane.
before_all do
  cocoapods  
  ensure_git_status_clean
  sigh
end

lane :Store do
  increment_build_number
  commit_version_bump
  add_git_tag
  pilot(skip_submission: true)
end
